[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "gua"
authors = [{name = "Luis Fernando Victor", email = "luis.fdo.victor.g@gmail.com"}]
dynamic = ["version", "description"]
